//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientDB()
        {
            this.ContactDB = new ObservableListSource<ContactDB>();
        }
    
        public int idClient { get; set; }
        public string raisonSocial { get; set; }
        public string type { get; set; }
        public string activite { get; set; }
        public string nature { get; set; }
        public int effectifs { get; set; }
        public decimal ca { get; set; }
        public string comment { get; set; }
        public string telephone { get; set; }
        public string rue { get; set; }
        public string codePostal { get; set; }
        public string ville { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ContactDB> ContactDB { get; set; }
    }
}
