//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientDB()
        {
            this.ContactDB = new HashSet<ContactDB>();
        }
    
        public int idClient { get; set; }
        public string raisonSocial { get; set; }
        public string type { get; set; }
        public string activite { get; set; }
        public string nature { get; set; }
        public int effectifs { get; set; }
        public decimal ca { get; set; }
        public string comment { get; set; }
        public string telephone { get; set; }
        public string rue { get; set; }
        public string codePostal { get; set; }
        public string ville { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactDB> ContactDB { get; set; }
    }
}
