//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDB
    {
        public int idContact { get; set; }
        public int idClient { get; set; }
        public string nom { get; set; }
        public string fonction { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
    
        public virtual ClientDB ClientDB { get; set; }
    }
}
